baseURL = 'http://ppuerta.github.io/'
languageCode = 'en-us'
title = 'Pedro Puerta'
theme = "hallo"    
[Author]
    name = "Pedro"
[params]
    greeting = "Hello!"
    [[params.links]]
        iconset = "fas"
        icon = "envelope"
        title = "E-mail"
        url = "mailto:ppuerta@protonmail.com"
    [[params.links]]
        icon = "linkedin"
        title = "LinkedIn"
        url = "https://linkedin.com/ppuerta"
    [[params.links]]
        icon = "github"
        title = "Github"
        url = "https://github.com/ppuerta"    
    [[params.links]]
        icon = "medium"
        title = "Medium"
        url = "https://medium.com/@ppuertab"
    [[params.links]]
        iconorigin = "ai"
        iconset = "ai"
        icon = "cv"
        title = "CV"
        url = ""

    [params.colors]
        background = "#81c6ff"
        foreground = "#edf7ff"
        hover = "#ffba82"


